# Generated by Django 4.2.2 on 2025-02-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientName', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=60)),
                ('Contactno', models.BigIntegerField()),
                ('Emailid', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=15)),
                ('Status', models.CharField(max_length=15)),
            ],
        ),
    ]
