# Generated by Django 4.2.2 on 2025-02-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=35)),
                ('Password', models.CharField(max_length=10)),
                ('Utype', models.CharField(max_length=20)),
            ],
        ),
    ]
