# Generated by Django 4.2.2 on 2025-02-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_dtls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buildingid', models.CharField(max_length=100)),
                ('CompanyName', models.CharField(max_length=100)),
            ],
        ),
    ]
