# Generated by Django 4.2.2 on 2025-02-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_id', models.CharField(max_length=255)),
                ('building_id', models.CharField(max_length=255)),
                ('company_id', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('vehicle_id', models.CharField(max_length=255)),
                ('vehicle_rate', models.CharField(max_length=100)),
                ('ownername', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('booking_date', models.DateField()),
                ('parking_hours', models.IntegerField()),
                ('no_of_vehicles', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=50)),
            ],
        ),
    ]
