# Generated by Django 4.2.2 on 2025-02-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_company_dtls'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicleid', models.CharField(max_length=100)),
                ('VehicleRate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleName', models.CharField(max_length=100)),
            ],
        ),
    ]
