# Generated by Django 4.2.2 on 2025-02-08 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_vehiclerate_vehicletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_dtls',
            name='Buildingid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.building_dtls'),
        ),
    ]
