# Generated by Django 4.2.2 on 2025-02-11 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_company_dtls_buildingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclerate',
            name='Vehicleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.vehicletype'),
        ),
    ]
