# Generated by Django 4.2.2 on 2025-02-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bankname', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
                ('Accountno', models.CharField(max_length=100)),
                ('Cardholder', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('IFSC', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
            ],
        ),
    ]
