# Generated by Django 5.0.4 on 2025-03-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientapp", "0005_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_time",
            field=models.CharField(default="", max_length=60),
        ),
    ]
