# Generated by Django 4.2.2 on 2025-02-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_vehiclerate_vehicleid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parkingdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bid', models.CharField(max_length=100)),
                ('Cid', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('T_Park_Area', models.CharField(max_length=100)),
                ('T_no_vehicle', models.CharField(max_length=100)),
                ('Vehi_type_id', models.CharField(max_length=100)),
                ('Veh_rate', models.CharField(max_length=100)),
                ('No_of_veh', models.CharField(max_length=100)),
            ],
        ),
    ]
