# Generated by Django 5.0.4 on 2025-03-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientapp", "0006_booking_booking_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_time",
            field=models.TimeField(),
        ),
    ]
