# Generated by Django 4.2.2 on 2025-02-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_parkingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingdetails',
            name='Veh_image',
            field=models.FileField(default='', upload_to='file'),
        ),
    ]
