# Generated by Django 4.2.2 on 2025-02-12 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_parkingdetails_veh_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdetails',
            name='Bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.building_dtls'),
        ),
        migrations.AlterField(
            model_name='parkingdetails',
            name='Cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.company_dtls'),
        ),
    ]
