# Generated by Django 4.2.2 on 2025-02-15 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_parkingdetails_bid_alter_parkingdetails_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingdetails',
            name='Vehi_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.vehicletype'),
        ),
    ]
