# Generated by Django 5.0.4 on 2025-02-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0009_alter_parkingdetails_vehi_type_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="bookingpayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Veh_Owner_Name", models.CharField(max_length=100)),
                ("Veh_Owner_Emailid", models.CharField(max_length=100)),
                ("Booking_id", models.CharField(default="", max_length=100)),
                ("Parking_id", models.CharField(max_length=100)),
                ("Paymnt_date", models.DateField()),
                ("Paymntamount", models.CharField(max_length=100)),
                ("Status", models.CharField(max_length=100)),
            ],
        ),
    ]
